### PR TITLE
Fix basix gui

### PR DESCRIPTION
**Pull request by TheLocust3**
Still no fix for the window opening to full screen on linux. @Math-ias can you confirm this?

### CODE REVIEW

**Comment by Math-ias** [comment]
Upon checking out this pull request I got the following error in eclipse:

Access restriction: The type SwingUtilities is not accessible due to restriction on required library /usr/lib/jvm/
 java-8-oracle/jre/lib/rt.jar

**Comment by TheLocust3** [comment]
That sounds like a problem on your system. Simon got this running fine

**Comment by Math-ias** [comment]
Fixed now when I try to compile I get the following error: The method getColumnCount() of type QueueModel must override a superclass method

**Comment by TheLocust3** [comment]
Hmmm it does override the superclass method

**Comment by Math-ias** [comment]
On my computer it looks like this:

screenshot - 08182015 - 05 56 27 pm

**Comment by Math-ias** [comment]
It is maximized vertically and not horizontally.

**Comment by TheLocust3** [comment]
Alright I can try to fix this in ~30 minutes

**Comment by Math-ias** [comment]
Also note that actionPerformed should not have <code>@Override</code> before it, if you are implementing an interface, override is not needed, override is only needed for overwriting things from when you extend other classes (abstract and normal).

**Pull request merged**
